-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."FactTrips"
(
    "Tripid" integer NOT NULL,
    "Dateid" integer,
    "Stationid" integer,
    "Truckid" integer,
    "WasteCollected" numeric,
    PRIMARY KEY ("Tripid")
);

CREATE TABLE IF NOT EXISTS public."DimTruck"
(
    "Truckid" integer NOT NULL,
    "TruckType" character varying(10),
    PRIMARY KEY ("Truckid")
);

CREATE TABLE IF NOT EXISTS public."DimDate"
(
    "Dateid" integer NOT NULL,
    "Date" timestamp without time zone,
    "Year" integer,
    "Quarter" integer,
    "QuarterName" character varying(3),
    month integer,
    "MonthName" character varying(10),
    "Day" integer,
    "WeekDay" integer,
    "WeekDayName" character varying(10),
    PRIMARY KEY ("Dateid")
);

CREATE TABLE IF NOT EXISTS public."DimStation"
(
    "Stationid" integer NOT NULL,
    "City" character varying(30),
    PRIMARY KEY ("Stationid")
);

ALTER TABLE IF EXISTS public."FactTrips"
    ADD FOREIGN KEY ("Dateid")
    REFERENCES public."DimDate" ("Dateid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactTrips"
    ADD FOREIGN KEY ("Stationid")
    REFERENCES public."DimStation" ("Stationid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FactTrips"
    ADD FOREIGN KEY ("Truckid")
    REFERENCES public."DimTruck" ("Truckid") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;